// The DB stores UUID primary/foreign keys as BINARY(16) (matching the Java
// backend's Hibernate UUID mapping), but they cross the JSON/HTTP boundary as
// standard dashed UUID strings - these convert between the two.

// Built via a plain (definitely ArrayBuffer-backed) Uint8Array rather than
// Node's Buffer.from(), which Prisma's generated Bytes field types reject -
// Buffer's backing store is typed as ArrayBufferLike (it also permits
// SharedArrayBuffer), while Prisma's Bytes setters require Uint8Array<ArrayBuffer>.
export function uuidToBuffer(uuid: string): Uint8Array<ArrayBuffer> {
  const hex = uuid.replace(/-/g, "");
  if (hex.length !== 32 || !/^[0-9a-fA-F]+$/.test(hex)) {
    throw new Error(`Invalid UUID: ${uuid}`);
  }
  const bytes = new Uint8Array(new ArrayBuffer(16));
  for (let i = 0; i < 16; i++) {
    bytes[i] = parseInt(hex.substring(i * 2, i * 2 + 2), 16);
  }
  return bytes;
}

export function bufferToUuid(buf: Buffer | Uint8Array | null | undefined): string | null {
  if (!buf) return null;
  const b = Buffer.isBuffer(buf) ? buf : Buffer.from(buf);
  const hex = b.toString("hex");
  return `${hex.slice(0, 8)}-${hex.slice(8, 12)}-${hex.slice(12, 16)}-${hex.slice(16, 20)}-${hex.slice(20)}`;
}
