# MySQL Configuration
db=mysql
db-url=jdbc:mysql://:3306/keycloak
db-username=keycloak
db-password=root

# # TLS Setup
# https-certificate-file=/path/to/cert.pem
# https-certificate-key-file=/path/to/key.pem

# Strict Hostname Matching
# hostname=auth.a2b-software.com
# hostname-strict=true